### ISSUE TITLE
wrong 3rd argument name of addAssetToToken

### ISSUE THREAD

**Issue by ilionic** [rmrk-team/evm-dev-docs#1] opened 2023-01-08 17:00 UTC
Should be `replacedAssetWithId` instead of `overwrites` 

![image](https://user-images.githubusercontent.com/1027871/211209158-6a7e7a05-06a8-4a34-9f2d-b85f06a25ded.png)

**Comment by ThunderDeliverer** [comment] 2023-01-08 18:37
@ilionic Could you please let me know the contract name?

**Comment by ThunderDeliverer** [comment] 2023-01-08 18:53
From what I gather, you are looking at a documentation of `addAssetToToken`, but the code shows a different function called `_addAssetToToken`.

**Comment by ilionic** [comment] 2023-01-08 19:06
> From what I gather, you are looking at a documentation of `addAssetToToken`, but the code shows a different function called `_addAssetToToken`.

Same as in `addAssetToToken`: 

https://github.com/rmrk-team/evm/blob/4861170938089bcbd97e6bcd39bf5e3028b14495/contracts/implementations/abstracts/RMRKAbstractMultiAssetImpl.sol#L56

**Comment by ThunderDeliverer** [comment] 2023-01-08 20:13
The documentation for this contract is correct: https://evm.rmrk.app/evm-contracts-documentation/implementations/abstracts/rmrkabstractmultiassetimpl#addassettotoken. Were you looking at https://evm.rmrk.app/rmrk-legos-examples/multiasset#addassettotoken?

**Comment by ThunderDeliverer** [comment] 2023-01-08 20:21
I think this was the case. Thank you for pointing it out, the issue is fixed in https://github.com/rmrk-team/evm-dev-docs/commit/726b45e86f3aa3560514900827e61ec7c979928f

**Closed as completed by ThunderDeliverer** 2023-01-08 20:21 UTC
